### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by st-clair-clarke** [e-cloud/ng2-permission#1]
Hi,
Could we have some idea please how to use your package?

I see it marked as ng2, can I assume it is compatible with ng4?

Cheers

**Comment by e-cloud** [comment]
@st-clair-clarke I've updated the readme, have a look and post comment if you has problems

**Comment by st-clair-clarke** [comment]
Thanks.
I will try to use it and get back to you.

Cheers

**Comment by e-cloud** [comment]
closing as inactive
