### ISSUE TITLE
ERROR in : Unexpected value 'Ng2Permission

### ISSUE THREAD

**Issue by frontendjorge** [e-cloud/ng2-permission#2]
In the last version of Node JS and Angular when you try to build for production the terminal show the follow message

"ERROR in : Unexpected value 'Ng2Permission in C:/Users/Jorge Suarez/Documents/Cheil/unique_forms/node_modules/angular2-permission/dist/module/ng2-permission.module
.d.ts' imported by the module 'AppModule in C:/Users/Jorge Suarez/Documents/Cheil/unique_forms/src/app/app.module.ts'. Please add a @NgModule annotation."

----

the module was installed and  imported

**Comment by e-cloud** [comment]
hey, man, you've gone to the wrong reporsitory. @frontendjorge

**Comment by frontendjorge** [comment]
> hey, man, you've gone to the wrong reporsitory. @frontendjorge

Yes. I'm sorry.

**Comment by e-cloud** [comment]
BTW, you could give it a try to this library 😉
